In [1]:
# Import Libraries
import pandas as pd
import numpy as np

In [2]:
# load DataSet
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()

In [3]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [4]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [5]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [6]:
data.target_names


array(['malignant', 'benign'], dtype='<U9')

In [8]:
df = pd.DataFrame(np.c_[data.data,data.target],columns = [list(data.feature_names)+['target']])
df.head()


mean radius mean texture mean perimeter mean area mean smoothness  \
0       17.99        10.38         122.80    1001.0         0.11840   
1       20.57        17.77         132.90    1326.0         0.08474   
2       19.69        21.25         130.00    1203.0         0.10960   
3       11.42        20.38          77.58     386.1         0.14250   
4       20.29        14.34         135.10    1297.0         0.10030   

  mean compactness mean concavity mean concave points mean symmetry  \
0          0.27760         0.3001             0.14710        0.2419   
1          0.07864         0.0869             0.07017        0.1812   
2          0.15990         0.1974             0.12790        0.2069   
3          0.28390         0.2414             0.10520        0.2597   
4          0.13280         0.1980             0.10430        0.1809   

  mean fractal dimension  ... worst texture worst perimeter worst area  \
0                0.07871  ...         17.33          184.60     2019.0   
1                0.05667  ...         23.41          158.80     1956.0   
2                0.05999  ...         25.53          152.50     1709.0   
3                0.09744  ...         26.50           98.87      567.7   
4                0.05883  ...         16.67          152.20     1575.0   

  worst smoothness worst compactness worst concavity worst concave points  \
0           0.1622            0.6656          0.7119               0.2654   
1           0.1238            0.1866          0.2416               0.1860   
2           0.1444            0.4245          0.4504               0.2430   
3           0.2098            0.8663          0.6869               0.2575   
4           0.1374            0.2050          0.4000               0.1625   

  worst symmetry worst fractal dimension target  
0         0.4601                 0.11890    0.0  
1         0.2750                 0.08902    0.0  
2         0.3613                 0.08758    0.0  
3         0.6638                 0.17300    0.0  
4         0.2364                 0.07678    0.0  

[5 rows x 31 columns]

In [9]:
df.tail()

mean radius mean texture mean perimeter mean area mean smoothness  \
564       21.56        22.39         142.00    1479.0         0.11100   
565       20.13        28.25         131.20    1261.0         0.09780   
566       16.60        28.08         108.30     858.1         0.08455   
567       20.60        29.33         140.10    1265.0         0.11780   
568        7.76        24.54          47.92     181.0         0.05263   

    mean compactness mean concavity mean concave points mean symmetry  \
564          0.11590        0.24390             0.13890        0.1726   
565          0.10340        0.14400             0.09791        0.1752   
566          0.10230        0.09251             0.05302        0.1590   
567          0.27700        0.35140             0.15200        0.2397   
568          0.04362        0.00000             0.00000        0.1587   

    mean fractal dimension  ... worst texture worst perimeter worst area  \
564                0.05623  ...         26.40          166.10     2027.0   
565                0.05533  ...         38.25          155.00     1731.0   
566                0.05648  ...         34.12          126.70     1124.0   
567                0.07016  ...         39.42          184.60     1821.0   
568                0.05884  ...         30.37           59.16      268.6   

    worst smoothness worst compactness worst concavity worst concave points  \
564          0.14100           0.21130          0.4107               0.2216   
565          0.11660           0.19220          0.3215               0.1628   
566          0.11390           0.30940          0.3403               0.1418   
567          0.16500           0.86810          0.9387               0.2650   
568          0.08996           0.06444          0.0000               0.0000   

    worst symmetry worst fractal dimension target  
564         0.2060                 0.07115    0.0  
565         0.2572                 0.06637    0.0  
566         0.2218                 0.07820    0.0  
567         0.4087                 0.12400    0.0  
568         0.2871                 0.07039    1.0  

[5 rows x 31 columns]

In [10]:
df.shape

(569, 31)

In [11]:
X = df.iloc[:, 0:-1]
y = df.iloc[:,-1]

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=51)

print('Shape of X_train =' , X_train.shape)
print('Shape of X_test = ' , X_test.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of y_test =', y_test.shape)


Shape of X_train = (455, 30)
Shape of X_test =  (114, 30)
Shape of y_train =  (455,)
Shape of y_test = (114,)


# Train Support Vector Classification Model

In [16]:
from sklearn.svm import SVC


In [17]:
#SVC()
# Init signature:
# SVC(
#     *,
#     C=1.0,
#     kernel='rbf',
#     degree=3,
#     gamma='scale',
#     coef0=0.0,
#     shrinking=True,
#     probability=False,
#     tol=0.001,
#     cache_size=200,
#     class_weight=None,
#     verbose=False,
#     max_iter=-1,
#     decision_function_shape='ovr',
#     break_ties=False,
#     random_state=None,
# )
# Docstring:     
# C-Support Vector Classification.

# The implementation is based on libsvm. The fit time scales at least
# quadratically with the number of samples and may be impractical
# beyond tens of thousands of samples. For large datasets
# consider using :class:`~sklearn.svm.LinearSVC` or
# :class:`~sklearn.linear_model.SGDClassifier` instead, possibly after a
# :class:`~sklearn.kernel_approximation.Nystroem` transformer.

# The multiclass support is handled according to a one-vs-one scheme.

# For details on the precise mathematical formulation of the provided
# kernel functions and how `gamma`, `coef0` and `degree` affect each
# other, see the corresponding section in the narrative documentation:
# :ref:`svm_kernels`.

# Read more in the :ref:`User Guide <svm_classification>`.

# Parameters
# ----------
# C : float, default=1.0
#     Regularization parameter. The strength of the regularization is
#     inversely proportional to C. Must be strictly positive. The penalty
#     is a squared l2 penalty.

# kernel : {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable,          default='rbf'
#     Specifies the kernel type to be used in the algorithm.
#     If none is given, 'rbf' will be used. If a callable is given it is
#     used to pre-compute the kernel matrix from data matrices; that matrix
#     should be an array of shape ``(n_samples, n_samples)``.

# degree : int, default=3
#     Degree of the polynomial kernel function ('poly').
#     Ignored by all other kernels.

# gamma : {'scale', 'auto'} or float, default='scale'
#     Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.

#     - if ``gamma='scale'`` (default) is passed then it uses
#       1 / (n_features * X.var()) as value of gamma,
#     - if 'auto', uses 1 / n_features.

#     .. versionchanged:: 0.22
#        The default value of ``gamma`` changed from 'auto' to 'scale'.

# coef0 : float, default=0.0
#     Independent term in kernel function.
#     It is only significant in 'poly' and 'sigmoid'.

# shrinking : bool, default=True
#     Whether to use the shrinking heuristic.
#     See the :ref:`User Guide <shrinking_svm>`.

# probability : bool, default=False
#     Whether to enable probability estimates. This must be enabled prior
#     to calling `fit`, will slow down that method as it internally uses
#     5-fold cross-validation, and `predict_proba` may be inconsistent with
#     `predict`. Read more in the :ref:`User Guide <scores_probabilities>`.

# tol : float, default=1e-3
#     Tolerance for stopping criterion.

# cache_size : float, default=200
#     Specify the size of the kernel cache (in MB).

# class_weight : dict or 'balanced', default=None
#     Set the parameter C of class i to class_weight[i]*C for
#     SVC. If not given, all classes are supposed to have
#     weight one.
#     The "balanced" mode uses the values of y to automatically adjust
#     weights inversely proportional to class frequencies in the input data
#     as ``n_samples / (n_classes * np.bincount(y))``.

# verbose : bool, default=False
#     Enable verbose output. Note that this setting takes advantage of a
#     per-process runtime setting in libsvm that, if enabled, may not work
#     properly in a multithreaded context.

# max_iter : int, default=-1
#     Hard limit on iterations within solver, or -1 for no limit.

# decision_function_shape : {'ovo', 'ovr'}, default='ovr'
#     Whether to return a one-vs-rest ('ovr') decision function of shape
#     (n_samples, n_classes) as all other classifiers, or the original
#     one-vs-one ('ovo') decision function of libsvm which has shape
#     (n_samples, n_classes * (n_classes - 1) / 2). However, one-vs-one
#     ('ovo') is always used as multi-class strategy. The parameter is
#     ignored for binary classification.

#     .. versionchanged:: 0.19
#         decision_function_shape is 'ovr' by default.

#     .. versionadded:: 0.17
#        *decision_function_shape='ovr'* is recommended.

#     .. versionchanged:: 0.17
#        Deprecated *decision_function_shape='ovo' and None*.

# break_ties : bool, default=False
#     If true, ``decision_function_shape='ovr'``, and number of classes > 2,
#     :term:`predict` will break ties according to the confidence values of
#     :term:`decision_function`; otherwise the first class among the tied
#     classes is returned. Please note that breaking ties comes at a
#     relatively high computational cost compared to a simple predict.

#     .. versionadded:: 0.22

# random_state : int, RandomState instance or None, default=None
#     Controls the pseudo random number generation for shuffling the data for
#     probability estimates. Ignored when `probability` is False.
#     Pass an int for reproducible output across multiple function calls.
#     See :term:`Glossary <random_state>`.

# Attributes
# ----------
# class_weight_ : ndarray of shape (n_classes,)
#     Multipliers of parameter C for each class.
#     Computed based on the ``class_weight`` parameter.

# classes_ : ndarray of shape (n_classes,)
#     The classes labels.

# coef_ : ndarray of shape (n_classes * (n_classes - 1) / 2, n_features)
#     Weights assigned to the features (coefficients in the primal
#     problem). This is only available in the case of a linear kernel.

#     `coef_` is a readonly property derived from `dual_coef_` and
#     `support_vectors_`.

# dual_coef_ : ndarray of shape (n_classes -1, n_SV)
#     Dual coefficients of the support vector in the decision
#     function (see :ref:`sgd_mathematical_formulation`), multiplied by
#     their targets.
#     For multiclass, coefficient for all 1-vs-1 classifiers.
#     The layout of the coefficients in the multiclass case is somewhat
#     non-trivial. See the :ref:`multi-class section of the User Guide
#     <svm_multi_class>` for details.

# fit_status_ : int
#     0 if correctly fitted, 1 otherwise (will raise warning)

# intercept_ : ndarray of shape (n_classes * (n_classes - 1) / 2,)
#     Constants in decision function.

# n_features_in_ : int
#     Number of features seen during :term:`fit`.

#     .. versionadded:: 0.24

# feature_names_in_ : ndarray of shape (`n_features_in_`,)
#     Names of features seen during :term:`fit`. Defined only when `X`
#     has feature names that are all strings.

#     .. versionadded:: 1.0

# support_ : ndarray of shape (n_SV)
#     Indices of support vectors.

# support_vectors_ : ndarray of shape (n_SV, n_features)
#     Support vectors.

# n_support_ : ndarray of shape (n_classes,), dtype=int32
#     Number of support vectors for each class.

# probA_ : ndarray of shape (n_classes * (n_classes - 1) / 2)
# probB_ : ndarray of shape (n_classes * (n_classes - 1) / 2)
#     If `probability=True`, it corresponds to the parameters learned in
#     Platt scaling to produce probability estimates from decision values.
#     If `probability=False`, it's an empty array. Platt scaling uses the
#     logistic function
#     ``1 / (1 + exp(decision_value * probA_ + probB_))``
#     where ``probA_`` and ``probB_`` are learned from the dataset [2]_. For
#     more information on the multiclass case and training procedure see
#     section 8 of [1]_.

# shape_fit_ : tuple of int of shape (n_dimensions_of_X,)
#     Array dimensions of training vector ``X``.

# See Also
# --------
# SVR : Support Vector Machine for Regression implemented using libsvm.

# LinearSVC : Scalable Linear Support Vector Machine for classification
#     implemented using liblinear. Check the See Also section of
#     LinearSVC for more comparison element.

# References
# ----------
# .. [1] `LIBSVM: A Library for Support Vector Machines
#     <http://www.csie.ntu.edu.tw/~cjlin/papers/libsvm.pdf>`_

# .. [2] `Platt, John (1999). "Probabilistic outputs for support vector
#     machines and comparison to regularizedlikelihood methods."
#     <http://citeseer.ist.psu.edu/viewdoc/summary?doi=10.1.1.41.1639>`_

# Examples
# --------
# >>> import numpy as np
# >>> from sklearn.pipeline import make_pipeline
# >>> from sklearn.preprocessing import StandardScaler
# >>> X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
# >>> y = np.array([1, 1, 2, 2])
# >>> from sklearn.svm import SVC
# >>> clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
# >>> clf.fit(X, y)
# Pipeline(steps=[('standardscaler', StandardScaler()),
#                 ('svc', SVC(gamma='auto'))])

# >>> print(clf.predict([[-0.8, -1]]))

# SVC Kernel RBF(Radial Basis Function)

In [20]:
classification_rbf = SVC(kernel = 'rbf')
classification_rbf.fit(X_train ,y_train)

C:\Users\shubh\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(


SVC()

In [22]:
classification_rbf.score(X_test,y_test)

C:\Users\shubh\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(


0.9035087719298246

# Feature Scaling

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
sc = StandardScaler()

In [30]:
sc.fit(X_train)

C:\Users\shubh\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(


StandardScaler()

In [31]:
X_train_sc = sc.transform(X_train)
X_test_sc = sc.transform(X_test)

C:\Users\shubh\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\shubh\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(


In [32]:
classification_rbf_sc = SVC(kernel = 'rbf')
classification_rbf_sc.fit(X_train_sc ,y_train)


SVC()

In [34]:
classification_rbf_sc.score(X_test_sc,y_test)

0.9473684210526315

# SVC Kernel polynomial(poly)

In [40]:
classification_poly = SVC(kernel = 'poly',degree = 2)
classification_poly.fit(X_train_sc ,y_train)
classification_poly.score(X_test_sc,y_test)

0.7982456140350878

# SVC Kernel Linear

In [41]:
classification_linear = SVC(kernel = 'linear')
classification_linear.fit(X_train_sc ,y_train)
classification_linear.score(X_test_sc,y_test)

0.9473684210526315

In [42]:
# Predict Cancer

patient1 = [17.99,
 10.38,
 122.8,
 1001.0,
 0.1184,
 0.2776,
 0.3001,
 0.1471,
 0.2419,
 0.07871,
 1.095,
 0.9053,
 8.589,
 153.4,
 0.006399,
 0.04904,
 0.05373,
 0.01587,
 0.03003,
 0.006193,
 25.38,
 17.33,
 184.6,
 2019.0,
 0.1622,
 0.6656,
 0.7119,
 0.2654,
 0.4601,
 0.1189]
 

In [43]:
patient1_sc = sc.transform(np.array([patient1]))
patient1_sc

array([[ 1.08251028, -2.12451742,  1.25006067,  0.97254965,  1.46781549,
         3.16232325,  2.55846034,  2.48486634,  2.09624644,  2.08993201,
         2.35827558, -0.60226207,  2.66093534,  2.33053219, -0.23730082,
         1.19245085,  0.62261841,  0.57360654,  1.02616522,  0.80379075,
         1.88782615, -1.39038516,  2.29703524,  2.00795595,  1.24539341,
         2.53896053,  2.0206957 ,  2.25059294,  2.65132987,  1.82722173]])

In [46]:
pred = classification_linear.predict(patient1_sc)
pred

array([0.])

In [47]:
if pred[0] == 0:
    print("Patient has Cancer(maligant tumor)")
else:
    print('Patient has no cancer(maligant benign)')

Patient has Cancer(maligant tumor)
