In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# New section

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# importing the dataset
dataset = pd.read_csv('inputt23.csv')
X = dataset.iloc[:,0:20]
y = dataset.iloc[:, 20]
dataset.head(20)

lon        lat  altitude  aspect  dd  dis_dr  dis_faults  dis_riv  \
0   78.871297  24.311751         1       5   5       3           5        4   
1   78.881297  24.311751         1       1   5       3           5        5   
2   78.891297  24.311751         1       5   5       3           5        5   
3   78.901297  24.311751         1       1   5       3           5        5   
4   78.911297  24.311751         1       3   5       3           5        5   
5   78.921297  24.311751         1       5   5       3           5        5   
6   78.931297  24.311751         1       2   5       3           5        5   
7   78.861297  24.321751         1       2   0       0           5        4   
8   78.871297  24.321751         1       2   5       3           5        4   
9   78.881297  24.321751         1       3   5       3           5        5   
10  78.891297  24.321751         1       2   5       3           5        5   
11  78.901297  24.321751         1       4   5       3           5        5   
12  78.911297  24.321751         1       5   5       3           5        5   
13  78.921297  24.321751         1       1   5       3           5        5   
14  78.931297  24.321751         1       1   5       3           5        5   
15  78.941297  24.321751         1       3   5       3           4        5   
16  78.951297  24.321751         1       2   5       3           4        5   
17  78.961297  24.321751         1       1   5       3           5        5   
18  78.971297  24.321751         1       1   5       3           5        5   
19  78.981297  24.321751         1       2   5       3           5        5   

    dis_road  geomorphol  ...  lithology1  lulc  ndvi  plan_curv  rainfall1  \
0          4           5  ...           0     2     3          2          3   
1          4           5  ...           0     2     4          2          3   
2          4           5  ...           2     1     4          4          3   
3          4           9  ...           3     3     3          3          3   
4          4           7  ...           2     4     3          4          3   
5          4           5  ...           2     3     5          2          3   
6          4           5  ...           5     2     2          3          3   
7          4           7  ...           2     2     3          4          3   
8          4           7  ...           2     3     2          2          3   
9          4           7  ...           3     3     2          3          3   
10         4           7  ...           3     3     3          2          3   
11         4           7  ...           3     3     2          3          3   
12         4           7  ...           2     3     3          2          3   
13         4           7  ...           2     2     4          3          3   
14         4           7  ...           2     3     4          4          3   
15         4           5  ...           2     3     4          5          3   
16         4           7  ...           3     2     2          3          3   
17         4           7  ...           3     2     3          4          3   
18         4           7  ...           3     1     5          3          3   
19         4           7  ...           3     2     3          3          3   

    rofile_cur  slope  soil1  twi  GWPZ  
0            3      3      7    4     0  
1            4      3      7    4     0  
2            5      3      7    4     1  
3            3      4      7    4     4  
4            4      5      7    2     4  
5            5      2      7    4     1  
6            4      4      7    4     2  
7            4      5      7    2     0  
8            3      4      7    4     3  
9            4      5      7    3     4  
10           3      4      7    4     3  
11           4      5      7    2     4  
12           3      5      7    3     3  
13           3      5      7    3     3  
14           4      5      7    4     3  
15           4    

In [ ]:
# Split dataset into training set and test set
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=109) # 70% training and 30% test
#Generating Model

X_train=X_train1.iloc[:, 2:20]
X_test=X_test1.iloc[:, 2:20]
#Import svm model
from sklearn.svm import SVR

#Create a svm Classifier
regressor = SVR(kernel='linear') # Linear Kernel

#Train the model using the training sets
regressor.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = regressor.predict(X_test)
y_pred01 = regressor.predict(X_train)
y_pred01

array([2.19238276, 4.34568879, 3.86900601, ..., 2.91996515, 2.60553299,
       3.36655272])

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(max_depth=2, random_state=0)
regressor.fit(X_train, y_train)
y_pred2 = regressor.predict(X_test)
y_pred02 = regressor.predict(X_train)



In [ ]:
#First Method Contains n^2 time complexity:

# #from sklearn.metrics import mean_absolute_error
# import numpy as np
# y_true = np.array(y_test)
# print(y_true)
# y_pred_arr = np.array(y_pred)
# print(y_pred_arr)

[2 3 4 ... 3 5 3]
[2.22050683 3.71141277 3.59779062 ... 3.73799424 4.12921803 3.29510001]


In [ ]:
# def naive_roc_auc_score(y_true, y_pred_arr):
    
#   num_same_sign = 0
#   num_pairs = 0
  
#   for a in range(len(y_true)):
#     for b in range(len(y_true)):
#       if y_true[a] > y_true[b]:
#         num_pairs += 1
#         if y_pred_arr[a] > y_pred_arr[b]:
#           num_same_sign += 1
#         elif y_pred_arr[a] == y_pred_arr[b]:
#           num_same_sign += .5
        
#   return num_same_sign / num_pairs

In [ ]:
#from sklearn.metrics import mean_absolute_error
#print('mean_absolute_error:',mean_absolute_error(y_true,y_pred_arr))
#print('naive_roc_auc_score:',naive_roc_auc_score(y_true,y_pred_arr))

mean_absolute_error: 0.39787190225056124
naive_roc_auc_score: 0.9556932956345826


In [ ]:
#Second Method Contains order of n time complexity

def regression_roc_auc_score(y_test, y_pred, num_rounds = 10000):
  """
  Computes Regression-ROC-AUC-score.
  
  Parameters:
  ----------
  y_true: array-like of shape (n_samples,). Binary or continuous target variable.
  y_pred: array-like of shape (n_samples,). Target scores.
  num_rounds: int or string. If integer, number of random pairs of observations. 
              If string, 'exact', all possible pairs of observations will be evaluated.
  
  Returns:
  -------
  rroc: float. Regression-ROC-AUC-score.
  """
  
  import numpy as np
    
  y_test = np.array(y_test)
  y_pred = np.array(y_pred)

  num_pairs = 0
  num_same_sign = 0
  
  for i, j in _yield_pairs(y_test, num_rounds):
    diff_true = y_test[i] - y_test[j]
    diff_score = y_pred[i] - y_pred[j]
    if diff_true * diff_score > 0:
      num_same_sign += 1
    elif diff_score == 0:
      num_same_sign += .5
    num_pairs += 1
      
  return num_same_sign / num_pairs




In [ ]:
print('regression_roc_auc_score:',regression_roc_auc_score(y_test, y_pred, num_rounds = 10000))


regression_roc_auc_score: 0.9548


In [ ]:
from sklearn import metrics
print('Mean Absolute Error:',metrics.mean_absolute_error(y_test,y_pred))
print('Mean Squared Error:',metrics.mean_squared_error(y_test,y_pred))
print('Root Mean Squared Error:',np.sqrt(metrics.mean_squared_error(y_test,y_pred)))
print('Mean Absolute Error:',metrics.r2_score(y_test,y_pred))

Mean Absolute Error: 0.39787190225056124
Mean Squared Error: 0.31538650134703844
Root Mean Squared Error: 0.5615928252275294
Mean Absolute Error: 0.7655002217803957


In [ ]:
from sklearn import metrics
print('Mean Absolute Error:',metrics.mean_absolute_error(y_train,y_pred01))
print('Mean Squared Error:',metrics.mean_squared_error(y_train,y_pred01))
print('Root Mean Squared Error:',np.sqrt(metrics.mean_squared_error(y_train,y_pred01)))
print('Mean Absolute Error:',metrics.r2_score(y_train,y_pred01))

Mean Absolute Error: 0.40265863299823085
Mean Squared Error: 0.3673817508828496
Root Mean Squared Error: 0.6061202445743332
Mean Absolute Error: 0.7279953977073708


In [ ]:
from sklearn import metrics
print('Mean Absolute Error:',metrics.mean_absolute_error(y_test,y_pred2))
print('Mean Squared Error:',metrics.mean_squared_error(y_test,y_pred2))
print('Root Mean Squared Error:',np.sqrt(metrics.mean_squared_error(y_test,y_pred2)))
print('Mean Absolute Error:',metrics.r2_score(y_test,y_pred2))

Mean Absolute Error: 0.7939602361605502
Mean Squared Error: 1.0136437620155632
Root Mean Squared Error: 1.0067987693752725
Mean Absolute Error: 0.24632399810675332


In [ ]:
X_test


# New Section

In [ ]:
y_pred.shape

(4784,)

In [ ]:
dataset1 = pd.read_csv('/content/drive/MyDrive/TRAININGDATA2K.csv')

X2 = dataset1.iloc[:, 2:21]

In [ ]:
X2

In [ ]:
#Predict the response for test dataset
y_pred3 = clf.predict(X2)

In [ ]:
y_pred3

array([1, 1, 3, ..., 2, 2, 2])

In [ ]:
np.savetxt('y_pred5.txt' , y_pred3 , delimiter=',')

In [ ]:
#Split dataset into training set and test set
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=109) # 70% training and 30% test
#Generating Model

X_train=X_train1.iloc[:, 2:20]
X_test=X_test1.iloc[:, 2:20]
#Import svm model
from sklearn.svm import SVR

#Create a svm Classifier
regressor = SVR(kernel='linear') # Linear Kernel

#Train the model using the training sets
regressor.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = regressor.predict(X_test)


NameError: ignored